#!/usr/bin/with-contenv bash

if [ "$MODE" == "MASTER" ]; then
	exec s6-setuidgid smokeping /usr/sbin/smokeping --config="/etc/smokeping/config" --nodaemon
else
	exec s6-setuidgid smokeping /usr/local/bin/smokeping-slave-wrapper.sh
fi
